name: bonus_repository
description: A starting point for Dart libraries or applications.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.0.1

dependencies:
  bonus_api:
    path: ../bonus_api

  api_handler:
    path: ../api_handler

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
