name: api_handler
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.1

dependencies:
  dio: ^5.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
