name: bonus_api
description: A starting point for Dart libraries or applications.
version: 0.1.0

environment:
  sdk: ^3.0.1

dependencies:
  dio: ^5.1.2
  json_annotation: ^4.8.1
  retrofit: ^4.0.1

dev_dependencies:
  lints: ^2.0.0
  build_runner: ^2.4.4
  json_serializable: ^6.7.0
  retrofit_generator: ^7.0.1
  test: ^1.21.0
